### ISSUE TITLE
Compiling with buildTF.sh with other version of tensorflow

### ISSUE THREAD

**Issue by rizwanishaq** [githubharald/CTCWordBeamSearch#2]
Compiling the buildTF  only works with 1.3.0 version for other version, it gave the following error 

./buildTF.sh 
In file included from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/platform/mutex.h:31:0,
                 from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/op.h:32,
                 from ../src/TFWordBeamSearch.cpp:1:
/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/platform/default/mutex.h:25:22: fatal error: nsync_cv.h: No such file or directory
compilation terminated.

any solution?

**Comment by rizwanishaq** [comment]
TF version 1.5.0, also checked with 1.4.0, and 1.6.0 
OS (16.04.1-Ubuntu) 
and compiler version gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

**Comment by githubharald** [comment]
This works for TF1.6 on my system:

**File: buildTF.sh**
```
#!/bin/bash

TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
TF_LFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )

g++ -Wall -O2 --std=c++14 -shared -o TFWordBeamSearch.so ../src/TFWordBeamSearch.cpp ../src/main.cpp ../src/WordBeamSearch.cpp ../src/PrefixTree.cpp ../src/Metrics.cpp ../src/MatrixCSV.cpp ../src/LanguageModel.cpp ../src/DataLoader.cpp ../src/Beam.cpp -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -D_GLIBCXX_USE_CXX11_ABI=0
```

**Comment by rizwanishaq** [comment]
Thanks. It is working now.

**Comment by githubharald** [comment]
buildTF.sh handles TF 1.3, 1.4, 1.5 and 1.6 now.

**Comment by harirajeev** [comment]
will it work with TF 1.12 , i am getting below message
  from ._conv import register_converters as _register_converters
<command-line>:0:0: warning: "_GLIBCXX_USE_CXX11_ABI" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition

**Comment by weinman** [comment]
Yes, it works in TF1.12, See #12
